version: "3"

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - USER_SERVICE_URL=http://user-service:3001
      - PRODUCT_SERVICE_URL=http://product-service:3002
    depends_on:
      - user-service
      - product-service
    networks:
      - microservices-net

  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - MONGODB_URI=mongodb://mongo-user:27017/user-service
      - JWT_SECRET=your_very_secure_jwt_secret_key
    depends_on:
      - mongo-user
    networks:
      - microservices-net

  product-service:
    build: ./product-service
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - MONGODB_URI=mongodb://mongo-product:27017/product-service
    depends_on:
      - mongo-product
    networks:
      - microservices-net

  mongo-user:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-user-data:/data/db
    networks:
      - microservices-net

  mongo-product:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongo-product-data:/data/db
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge

volumes:
  mongo-user-data:
  mongo-product-data:
